package com.codeaide.service;

import com.codeaide.i18n.CodeAideBundle;
import com.codeaide.provider.common.MessageCallback;
import com.codeaide.provider.common.SDKResult;
import com.codeaide.provider.claude.ClaudeSDKBridge;
import com.codeaide.provider.codex.CodexSDKBridge;
import com.codeaide.settings.CodeaideSettingsService;
import com.codeaide.util.LanguageConfigService;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vcs.FilePath;
import com.intellij.openapi.vcs.changes.Change;
import com.intellij.openapi.vcs.changes.ChangesUtil;
import com.intellij.openapi.vcs.changes.ContentRevision;
import com.intellij.openapi.vcs.VcsException;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Git commit message generation service.
 * Responsible for generating AI-powered commit messages.
 */
public class GitCommitMessageService {

    private static final Logger LOG = Logger.getInstance(GitCommitMessageService.class);

    private static final int MAX_DIFF_LENGTH = 4000; // Limit diff length to avoid exceeding token limits
    // Skip line-by-line diffing for very large files (e.g. lock files):
    // splitting them is slow and the output would be truncated anyway
    private static final int MAX_FILE_CONTENT_LENGTH = 200_000;
    // Cap for the detail section appended to the commit message
    private static final int MAX_DETAIL_LINES = 400;
    // Cap for the inventory text embedded in prompts
    private static final int MAX_INVENTORY_CHARS = 12_000;
    // LCS cell budget for precise line-change counting
    private static final long MAX_LCS_CELLS = 25_000_000L;
    private static final String PROVIDER_CLAUDE = "claude";
    private static final String PROVIDER_CODEX = "codex";
    private static final String COMMIT_CHANNEL_ID = "git-commit-message";

    /**
     * Hard cap for one generation attempt. The underlying bridges have no overall
     * timeout of their own (a wedged daemon or a stalled child process can wait
     * forever), so the service enforces its own deadline to keep the commit UI
     * from hanging on the "generating..." placeholder indefinitely.
     */
    private static final long DEFAULT_GENERATION_TIMEOUT_MS = 120_000;

    /** Fan-out timeout: base margin covering daemon cold starts and the merge request. */
    private static final long FAN_OUT_BASE_TIMEOUT_MS = 90_000;
    /** Fan-out timeout: allowance per parallel wave of batch agents. */
    private static final long FAN_OUT_PER_WAVE_TIMEOUT_MS = 45_000;
    /** Fan-out timeout hard cap (10 minutes). */
    private static final long MAX_FAN_OUT_TIMEOUT_MS = 600_000;

    /**
     * Built-in commit prompt: role, output contract, Conventional Commits spec,
     * quality bar and one format example. Users can append additional prompts
     * via the settings page, which take priority.
     */
    private static final String BUILTIN_COMMIT_PROMPT = """
你是一位资深软件工程师，擅长阅读 git diff 并撰写高质量的 Conventional Commits 提交信息。

## 输出契约（最高优先级，必须严格遵守）
- 只输出一个 <commit></commit> 标签块，标签外不允许出现任何字符
- 不要输出分析过程、解释、客套话或 markdown 代码围栏
- description 和 body 的语言遵循下方「输出语言要求」部分；type、scope 一律使用英文

## 格式规范
<type>(<scope>): <subject>

<body>

<footer>

### type（必选，英文小写，只选一个最主要的）
- feat：新功能；fix：缺陷修复；refactor：重构（不改变外部行为）
- perf：性能优化；docs：文档；style：代码风格（不影响逻辑）
- test：测试；build：构建/依赖；ci：持续集成；chore：其他杂项；revert：回滚
- 功能与修复并存时，以对用户可见的变化为准

### scope（推荐，英文小写名词）
- 从 diff 的文件路径归纳模块名，如 auth、api、ui、deps、parser
- 全仓库性的改动可以省略 scope

### subject（必选）
- 祈使句、现在时：英文用 "add" 而非 "added"，中文直接以动词开头
- 不超过 50 个字符，概括"最重要的一个变化"，不罗列文件名
- 结尾不加句号；英文首字母小写

### body（可选，复杂变更时推荐）
- 与 subject 之间空一行，用 "- " 列出 2~5 个要点
- 写"做了什么、为什么这么做"，不写"怎么实现的"，不复述 diff 本身
- 每行不超过 72 个字符；琐碎的小改动不写 body

### footer（可选）
- 仅在存在破坏性变更或 issue 引用时书写
- 如：BREAKING CHANGE: ... / Closes #123

## 质量要求
- 从 diff 归纳改动意图；多个文件的同类改动合并表述
- 不堆砌文件名、函数名、变量名等实现细节
- 文件级明细清单由程序自动附加到最终结果，禁止在 body 中罗列文件
- 不出现署名、时间、"Generated by" 等元信息，不使用 emoji
- 不包含密钥、token、内部地址等敏感信息

## 示例（仅示范格式，不要照抄内容）
feat(auth): 支持扫码登录并自动刷新令牌

- 新增扫码登录入口，轮询二维码状态完成登录
- 令牌到期前自动刷新，避免频繁重新登录
""";

    // XML tags used to extract the commit message
    private static final String COMMIT_TAG_START = "<commit>";
    private static final String COMMIT_TAG_END = "</commit>";

    private final Project project;
    private final CodeaideSettingsService settingsService;
    private volatile ProgressCallback progressCallback;
    /** Interrupt runnables of every bridge this generation has spawned. */
    private final List<Runnable> bridgeCleanups = new CopyOnWriteArrayList<>();

    /**
     * Commit message generation callback interface.
     */
    public interface CommitMessageCallback {
        void onSuccess(String commitMessage);
        void onError(String error);
    }

    /**
     * Optional progress callback reporting the current generation stage.
     * The stage text is already localized and ready for display.
     */
    public interface ProgressCallback {
        void onStage(String stageText);
    }

    /**
     * Handle to cancel an in-flight generation. Cancellation is idempotent and
     * delivers a cancellation error to the original callback exactly once.
     */
    public interface GenerationHandle {
        void cancel();
    }

    public GitCommitMessageService(@NotNull Project project) {
        this.project = project;
        this.settingsService = new CodeaideSettingsService();
    }

    /**
     * Generate a commit message.
     *
     * @param changes  The selected file changes
     * @param callback The callback interface
     * @return a handle to cancel the in-flight generation
     */
    public GenerationHandle generateCommitMessage(
            @NotNull Collection<Change> changes,
            @NotNull CommitMessageCallback callback
    ) {
        return generateCommitMessage(changes, callback, null);
    }

    /**
     * Generate a commit message with optional stage progress reporting.
     *
     * @param changes          The selected file changes
     * @param callback         The callback interface
     * @param progressCallback Optional stage progress callback (nullable)
     * @return a handle to cancel the in-flight generation
     */
    public GenerationHandle generateCommitMessage(
            @NotNull Collection<Change> changes,
            @NotNull CommitMessageCallback callback,
            ProgressCallback progressCallback
    ) {
        this.progressCallback = progressCallback;

        List<Change> changeList = new ArrayList<>(changes);
        int batchSize = getCommitAgentBatchSize();
        int maxParallel = getCommitAgentMaxParallel();
        int batchCount = batchCount(changeList.size(), batchSize);
        boolean fanOut = batchCount > 1;

        reportStage("commit.stage.collecting");
        // Per-file change inventory (status + line counts), computed locally and
        // therefore instant. It feeds the detail section appended to the final
        // message and, for large change sets, the fan-out agents (compact input
        // keeps them fast).
        List<String> inventory = buildChangeInventory(changeList);
        String fileDetail = isCommitIncludeFileDetail() ? buildFileDetailSection(inventory) : null;
        CommitMessageCallback delegate = fileDetail == null ? callback : new CommitMessageCallback() {
            @Override
            public void onSuccess(String commitMessage) {
                callback.onSuccess(commitMessage + fileDetail);
            }

            @Override
            public void onError(String error) {
                callback.onError(error);
            }
        };

        TimeoutGuard guardedCallback = new TimeoutGuard(delegate, localized("commit.generateTimeout"));
        guardedCallback.arm(fanOut
                ? computeFanOutTimeoutMs(batchCount, maxParallel)
                : getGenerationTimeoutMs());
        // Interrupts every bridge created by this generation (single request,
        // fan-out batches and the merge request alike).
        guardedCallback.addTimeoutCleanup(this::runBridgeCleanups);
        try {
            if (fanOut) {
                // Large change set: one summary agent per batch of files running
                // in parallel, then one merge request — avoids the single-request
                // timeout that huge diffs would hit.
                generateWithFanOut(inventory, batchSize, maxParallel, guardedCallback);
            } else {
                // 1. Generate git diff
                String diff = generateGitDiff(changeList);
                if (diff.isEmpty()) {
                    guardedCallback.onError(localized("commit.noChangesFound"));
                    return () -> { };
                }

                // 2. Build the full prompt (built-in + user's additional prompt + diff)
                String fullPrompt = buildFullPrompt(diff);

                // 3. Call the AI SDK
                callAIService(fullPrompt, guardedCallback);
            }

        } catch (IOException e) {
            LOG.warn("AI service call failed", e);
            String message = e.getMessage();
            guardedCallback.onError(localized("commit.callApiFailed") + ": " + (message != null ? message : e.getClass().getSimpleName()));
        } catch (Exception e) {
            LOG.error("Failed to generate commit message", e);
            String message = e.getMessage();
            guardedCallback.onError(message != null ? message : e.getClass().getSimpleName());
        }
        return () -> guardedCallback.fail(localized("commit.generateCancelled"));
    }

    /**
     * Whether commit generation runs in fast mode (thinking/reasoning disabled).
     * Extracted for tests.
     */
    protected boolean isCommitFastMode() {
        try {
            return settingsService.getCommitFastMode();
        } catch (Exception e) {
            LOG.warn("Failed to read commit fast mode, using default: " + e.getMessage());
            return CodeaideSettingsService.DEFAULT_COMMIT_FAST_MODE;
        }
    }

    /**
     * Whether the per-file change detail list is appended to the commit message.
     * Extracted for tests.
     */
    protected boolean isCommitIncludeFileDetail() {
        try {
            return settingsService.getCommitIncludeFileDetail();
        } catch (Exception e) {
            LOG.warn("Failed to read commit include-file-detail, using default: " + e.getMessage());
            return CodeaideSettingsService.DEFAULT_COMMIT_INCLUDE_FILE_DETAIL;
        }
    }

    /**
     * Codex reasoning effort for commit generation: "low" in fast mode
     * (the bridge default is "medium"), null to use the provider default.
     */
    protected String getCodexReasoningEffort() {
        return isCommitFastMode() ? "low" : null;
    }

    /**
     * Overall timeout for one single-request generation. Extracted so tests can shorten it.
     */
    protected long getGenerationTimeoutMs() {
        return DEFAULT_GENERATION_TIMEOUT_MS;
    }

    /**
     * Fan-out timeout: a per-wave allowance for ceil(batches / parallel) waves
     * plus a base margin covering daemon cold starts and the merge request,
     * capped at {@link #MAX_FAN_OUT_TIMEOUT_MS}.
     */
    static long computeFanOutTimeoutMs(int batchCount, int maxParallel) {
        int waves = (int) Math.ceil(batchCount / (double) Math.max(1, maxParallel));
        return Math.min(MAX_FAN_OUT_TIMEOUT_MS,
                FAN_OUT_BASE_TIMEOUT_MS + FAN_OUT_PER_WAVE_TIMEOUT_MS * waves);
    }

    private static int batchCount(int changeCount, int batchSize) {
        if (changeCount <= 0) {
            return 0;
        }
        return (int) Math.ceil(changeCount / (double) Math.max(1, batchSize));
    }

    /**
     * Files each parallel commit agent summarizes (settings-backed). Extracted for tests.
     */
    protected int getCommitAgentBatchSize() {
        try {
            return settingsService.getCommitAgentBatchSize();
        } catch (Exception e) {
            LOG.warn("Failed to read commit agent batch size, using default: " + e.getMessage());
            return CodeaideSettingsService.DEFAULT_COMMIT_AGENT_BATCH_SIZE;
        }
    }

    /**
     * Maximum number of commit agents running in parallel (settings-backed). Extracted for tests.
     */
    protected int getCommitAgentMaxParallel() {
        try {
            return settingsService.getCommitAgentMaxParallel();
        } catch (Exception e) {
            LOG.warn("Failed to read commit agent max parallel, using default: " + e.getMessage());
            return CodeaideSettingsService.DEFAULT_COMMIT_AGENT_MAX_PARALLEL;
        }
    }

    private void registerBridgeCleanup(Runnable cleanup) {
        bridgeCleanups.add(cleanup);
    }

    private void runBridgeCleanups() {
        for (Runnable cleanup : bridgeCleanups) {
            try {
                cleanup.run();
            } catch (Exception e) {
                LOG.debug("Bridge cleanup failed: " + e.getMessage());
            }
        }
    }

    /**
     * Report the current generation stage to the optional progress callback.
     * A throwing callback must never break generation.
     */
    private void reportStage(String key, Object... params) {
        ProgressCallback progress = progressCallback;
        if (progress == null) {
            return;
        }
        try {
            progress.onStage(localized(key, params));
        } catch (Exception e) {
            LOG.debug("Progress callback threw for stage " + key, e);
        }
    }

    /**
     * Callback wrapper that guarantees exactly-once delivery and enforces a hard
     * timeout. The bridges below have paths that may never invoke their callback
     * at all (wedged daemon request, stalled child process, blocking daemon
     * shutdown); without this guard the commit box would show the
     * "generating..." placeholder forever.
     */
    static class TimeoutGuard implements CommitMessageCallback {
        private final CommitMessageCallback delegate;
        private final String timeoutMessage;
        private final AtomicBoolean completed = new AtomicBoolean(false);
        private final List<Runnable> timeoutCleanups = new CopyOnWriteArrayList<>();

        TimeoutGuard(CommitMessageCallback delegate, String timeoutMessage) {
            this.delegate = delegate;
            this.timeoutMessage = timeoutMessage;
        }

        /**
         * Arm the timeout. When it fires before any callback, the delegate
         * receives a timeout error and the registered cleanups run on
         * separate daemon threads (cleanups may block on wedged processes and
         * must never delay the error delivery itself).
         */
        void arm(long timeoutMs) {
            CompletableFuture.runAsync(
                    this::fireTimeout,
                    CompletableFuture.delayedExecutor(timeoutMs, TimeUnit.MILLISECONDS));
        }

        /**
         * Register best-effort cleanup (e.g. interrupting a provider channel or
         * shutting down the fan-out pool) executed when the timeout fires or the
         * generation is cancelled. Optional, multiple registrations allowed.
         */
        void addTimeoutCleanup(Runnable cleanup) {
            timeoutCleanups.add(cleanup);
        }

        private void fireTimeout() {
            LOG.warn("Commit message generation timed out");
            fail(timeoutMessage);
        }

        /**
         * Complete with an error exactly once, then run the registered cleanups
         * on separate daemon threads. Used by both the timeout and explicit
         * cancellation.
         */
        void fail(String message) {
            if (!completed.compareAndSet(false, true)) {
                return;
            }
            delegate.onError(message);
            runCleanup();
        }

        private void runCleanup() {
            for (Runnable cleanup : timeoutCleanups) {
                Thread cleanupThread = new Thread(cleanup, "commit-generation-timeout-cleanup");
                cleanupThread.setDaemon(true);
                cleanupThread.start();
            }
        }

        @Override
        public void onSuccess(String commitMessage) {
            if (completed.compareAndSet(false, true)) {
                delegate.onSuccess(commitMessage);
            }
        }

        @Override
        public void onError(String error) {
            if (completed.compareAndSet(false, true)) {
                delegate.onError(error);
            }
        }
    }

    /**
     * Generate git diff.
     */
    protected String generateGitDiff(@NotNull Collection<Change> changes) {
        StringBuilder diff = new StringBuilder();

        for (Change change : changes) {
            try {
                FilePath filePath = ChangesUtil.getFilePath(change);
                Change.Type changeType = change.getType();

                diff.append("\n=== ").append(changeType.name()).append(": ")
                        .append(filePath.getPath()).append(" ===\n");

                ContentRevision beforeRevision = change.getBeforeRevision();
                ContentRevision afterRevision = change.getAfterRevision();

                if (changeType == Change.Type.NEW && afterRevision != null) {
                    // New file: include content up to 500 characters
                    String content = afterRevision.getContent();
                    if (content != null && content.length() <= 500) {
                        diff.append("+++ ").append(content).append("\n");
                    } else if (content != null) {
                        diff.append("+++ [文件过大，仅显示前500字符]\n");
                        diff.append(content, 0, Math.min(500, content.length())).append("\n");
                    }
                } else if (changeType == Change.Type.DELETED && beforeRevision != null) {
                    // Deleted file marker
                    diff.append("--- 文件已删除\n");
                } else if (changeType == Change.Type.MODIFICATION && beforeRevision != null && afterRevision != null) {
                    // Modified file: generate a simple diff
                    String before = beforeRevision.getContent();
                    String after = afterRevision.getContent();

                    if (before != null && after != null) {
                        if (before.length() > MAX_FILE_CONTENT_LENGTH || after.length() > MAX_FILE_CONTENT_LENGTH) {
                            diff.append("~ [文件过大，已跳过逐行对比]\n");
                        } else {
                            diff.append(generateSimpleDiff(before, after));
                        }
                    }
                }

                // Limit total length
                if (diff.length() > MAX_DIFF_LENGTH) {
                    diff.append("\n... (diff 过长，已截断)");
                    break;
                }

            } catch (VcsException e) {
                LOG.warn("Failed to get diff for change: " + e.getMessage());
            }
        }

        return diff.toString();
    }

    /**
     * Generate a simple diff (showing added/removed lines).
     */
    private String generateSimpleDiff(String before, String after) {
        String[] beforeLines = before.split("\n");
        String[] afterLines = after.split("\n");

        StringBuilder diff = new StringBuilder();
        int maxLines = Math.max(beforeLines.length, afterLines.length);
        int shownLines = 0;
        int maxShownLines = 30; // Maximum lines to display

        for (int i = 0; i < maxLines && shownLines < maxShownLines; i++) {
            String beforeLine = i < beforeLines.length ? beforeLines[i] : "";
            String afterLine = i < afterLines.length ? afterLines[i] : "";

            if (!beforeLine.equals(afterLine)) {
                if (!beforeLine.isEmpty()) {
                    diff.append("- ").append(beforeLine).append("\n");
                    shownLines++;
                }
                if (!afterLine.isEmpty() && shownLines < maxShownLines) {
                    diff.append("+ ").append(afterLine).append("\n");
                    shownLines++;
                }
            }
        }

        if (maxLines > maxShownLines) {
            diff.append("... (更多变更已省略)\n");
        }

        return diff.toString();
    }

    /**
     * Get the user's additional prompt (optional).
     */
    private String getUserAdditionalPrompt() {
        try {
            String userPrompt = settingsService.getCommitPrompt();
            // Return empty if the user hasn't configured a prompt or set the default value
            if (userPrompt == null || userPrompt.trim().isEmpty()) {
                return "";
            }
            // Treat the old default value as not configured
            if (userPrompt.equals("你是一个commit提交专员，请你阅读git记录，帮我生成commit记录")) {
                return "";
            }
            return userPrompt.trim();
        } catch (Exception e) {
            LOG.warn("Failed to get user additional prompt from settings", e);
            return "";
        }
    }

    /**
     * Get the project-level additional prompt (optional).
     */
    private String getProjectAdditionalPrompt() {
        try {
            String projectPath = project.getBasePath();
            if (null == projectPath) {
                return "";
            }
            String projectPrompt = settingsService.getProjectCommitPrompt(projectPath);
            if (null == projectPrompt || projectPrompt.trim().isEmpty()) {
                return "";
            }
            return projectPrompt.trim();
        } catch (Exception e) {
            LOG.warn("get project additional prompt fail:", e);
            return "";
        }
    }

    /**
     * Get the i18n language code the commit message should be written in.
     * Follows the user's manually configured UI language, falling back to the IDE language.
     * Extracted as a protected method so tests can pin the language deterministically.
     */
    protected String getCommitOutputLanguage() {
        return LanguageConfigService.getCurrentLanguage(settingsService);
    }

    /**
     * Resolve a bundle message in the language the user has configured for the plugin
     * (manual override first, IDE language otherwise), rather than always using the IDE locale.
     */
    private String localized(String key, Object... params) {
        Locale locale = LanguageConfigService.getLocaleForLanguage(getCommitOutputLanguage());
        return CodeAideBundle.messageForLocale(key, locale, params);
    }

    /**
     * Build the full prompt.
     * Logic: built-in prompt + user's additional prompt + project-level additional prompt (highest priority)
     * + output language requirement (follows the configured UI language) + git diff.
     */
    private String buildFullPrompt(String diff) {
        StringBuilder prompt = new StringBuilder();

        // 1. Built-in commit prompt
        prompt.append(BUILTIN_COMMIT_PROMPT);

        // 2-3. User's global + project-level additional prompts
        appendUserAndProjectPrompts(prompt);

        // 4. Output language requirement (follows the current UI language setting; mandatory)
        appendOutputLanguageRequirement(prompt);

        // 5. Git diff content
        prompt.append("\n\n---\n\n");
        prompt.append("以下是 git diff 信息，请根据以上规则生成 commit message：\n\n");
        prompt.append("```diff\n");
        prompt.append(diff);
        prompt.append("\n```");

        // 6. Output format requirements (enforce XML tag wrapping for easy parsing)
        appendOutputFormatRequirements(prompt);

        return prompt.toString();
    }

    /**
     * Append the user's global additional prompt and the project-level additional
     * prompt (highest priority), when configured.
     */
    private void appendUserAndProjectPrompts(StringBuilder prompt) {
        // User's global additional prompt (if any)
        String userAdditionalPrompt = getUserAdditionalPrompt();
        if (!userAdditionalPrompt.isEmpty()) {
            prompt.append("\n\n## 用户附加要求（优先遵循）\n\n");
            prompt.append("以下是用户的额外要求，请在生成 commit message 时优先考虑这些要求：\n\n");
            prompt.append(userAdditionalPrompt);
        }

        // Project-level additional prompt (highest priority)
        String projectAdditionalPrompt = getProjectAdditionalPrompt();
        if (!projectAdditionalPrompt.isEmpty()) {
            prompt.append("\n\n## 项目专属要求\n\n");
            prompt.append("以下是当前项目的专属要求，与上述用户附加要求同时生效。当两者矛盾时，以此处项目要求为准：\n\n");
            prompt.append(projectAdditionalPrompt);
        }
    }

    /**
     * Append the mandatory output-language requirement derived from the
     * configured UI language.
     */
    private void appendOutputLanguageRequirement(StringBuilder prompt) {
        String outputLanguageName = LanguageConfigService.getLanguageDisplayName(getCommitOutputLanguage());
        prompt.append("\n\n## 输出语言要求（必须严格遵守）\n\n");
        prompt.append("- commit message 的 description 和 body 必须使用 ")
                .append(outputLanguageName).append(" 撰写\n");
        prompt.append("- type 和 scope 保持使用英文 Conventional Commits 关键字（如 feat、fix、chore）\n");
    }

    /**
     * Append the output format requirements (enforce XML tag wrapping for easy parsing).
     */
    private void appendOutputFormatRequirements(StringBuilder prompt) {
        prompt.append("\n\n【输出格式要求 - 必须严格遵守】\n");
        prompt.append("请将 commit message 用 XML 标签包裹输出，格式如下：\n");
        prompt.append("<commit>\n");
        prompt.append("type(scope): description\n");
        prompt.append("\n");
        prompt.append("optional body\n");
        prompt.append("</commit>\n\n");
        prompt.append("重要规则：\n");
        prompt.append("1. 必须使用 <commit> 和 </commit> 标签包裹\n");
        prompt.append("2. 标签外不要有任何其他内容（不要分析、不要解释、不要说明）\n");
    }

    /**
     * Fan-out generation for large change sets: each batch of inventory lines
     * gets a parallel summary agent; the summaries are merged into a single
     * commit message by one final request. Blocks the calling thread until done;
     * the timeout guard and its cleanups bound the wait.
     */
    private void generateWithFanOut(
            List<String> inventory,
            int batchSize,
            int maxParallel,
            TimeoutGuard guardedCallback
    ) throws IOException {
        JsonObject commitAiConfig = getCommitAiConfig();
        String effectiveProvider = getResolvedCommitAiProvider(commitAiConfig);
        if (effectiveProvider == null) {
            guardedCallback.onError(localized("commit.noAvailableProvider"));
            return;
        }

        List<List<String>> batches = new ArrayList<>();
        for (int i = 0; i < inventory.size(); i += batchSize) {
            batches.add(inventory.subList(i, Math.min(i + batchSize, inventory.size())));
        }
        LOG.info("Commit fan-out: " + inventory.size() + " files in " + batches.size()
                + " batches, maxParallel=" + maxParallel);

        reportStage("commit.stage.connecting");
        ExecutorService pool = Executors.newFixedThreadPool(Math.min(maxParallel, batches.size()));
        guardedCallback.addTimeoutCleanup(pool::shutdownNow);
        try {
            List<CompletableFuture<String>> futures = new ArrayList<>();
            for (int i = 0; i < batches.size(); i++) {
                final int batchIndex = i;
                final List<String> batch = batches.get(i);
                futures.add(CompletableFuture.supplyAsync(
                        () -> summarizeBatch(batch, batchIndex, batches.size(), inventory.size(), commitAiConfig, effectiveProvider),
                        pool));
            }

            List<String> summaries = new ArrayList<>();
            int finished = 0;
            for (CompletableFuture<String> future : futures) {
                String summary = null;
                try {
                    summary = future.join();
                } catch (Exception e) {
                    LOG.warn("Batch summary agent failed: " + e.getMessage());
                }
                finished++;
                reportStage("commit.stage.batch", finished, futures.size());
                if (summary != null && !summary.isEmpty()) {
                    summaries.add(summary);
                }
            }

            if (summaries.isEmpty()) {
                guardedCallback.onError(localized("commit.callApiFailed"));
                return;
            }

            reportStage("commit.stage.merging");
            String merged;
            try {
                merged = requestOnce(buildMergePrompt(summaries, inventory), commitAiConfig, effectiveProvider);
            } catch (InterruptedException e) {
                // Interrupted by the timeout guard / cancellation cleanup; the
                // guard has already delivered the outcome to the delegate.
                Thread.currentThread().interrupt();
                return;
            }
            guardedCallback.onSuccess(merged);
        } finally {
            pool.shutdownNow();
        }
    }

    /**
     * Summarize one batch of inventory lines for later merging. Returns "" when
     * the agent request failed (tolerated — the remaining batches still produce
     * a commit message).
     */
    private String summarizeBatch(
            List<String> batchLines,
            int index,
            int total,
            int totalFiles,
            JsonObject commitAiConfig,
            String provider
    ) {
        try {
            return requestOnce(buildBatchSummaryPrompt(batchLines, index, total, totalFiles), commitAiConfig, provider);
        } catch (Exception e) {
            LOG.warn("Batch " + (index + 1) + "/" + total + " summary failed: " + e.getMessage());
            return "";
        }
    }

    /**
     * Run one provider request and block until it completes. Used by the
     * fan-out batch agents and the merge request.
     */
    private String requestOnce(String prompt, JsonObject commitAiConfig, String provider)
            throws IOException, InterruptedException {
        CompletableFuture<String> future = new CompletableFuture<>();
        CommitMessageCallback single = new CommitMessageCallback() {
            @Override
            public void onSuccess(String commitMessage) {
                future.complete(commitMessage);
            }

            @Override
            public void onError(String error) {
                future.completeExceptionally(new RuntimeException(error));
            }
        };
        if (PROVIDER_CODEX.equals(provider)) {
            callCodexAPI(prompt, getResolvedCommitAiModel(commitAiConfig, PROVIDER_CODEX), single);
        } else {
            callClaudeAPI(prompt, getResolvedCommitAiModel(commitAiConfig, PROVIDER_CLAUDE), single);
        }
        try {
            return future.get();
        } catch (InterruptedException e) {
            future.cancel(true);
            throw e;
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            throw new IOException(cause != null ? cause.getMessage() : e.getMessage());
        }
    }

    /**
     * Build the per-batch summary prompt from inventory lines. The output
     * contract ("type: x" first line + bullet points, no tags) is deliberately
     * tag-free so the summaries pass the commit-message cleanup intact.
     */
    private String buildBatchSummaryPrompt(List<String> batchLines, int index, int total, int totalFiles) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("你是变更分析助手。整个提交涉及 ").append(totalFiles)
                .append(" 个文件的变更，已按文件分为 ").append(total)
                .append(" 批，以下是第 ").append(index + 1)
                .append(" 批的变更清单（格式：状态 路径 (+增/-删)，A=新增 M=修改 D=删除）。\n\n");
        prompt.append("请极简概括这批文件改动的意图，供后续合并生成 commit message：\n");
        prompt.append("1. 第一行只写：type: <类型>（类型从 feat / fix / refactor / perf / docs / style / test / build / ci / chore / revert 中选一个最主要的）\n");
        prompt.append("2. 第二行起用 1~3 个 \"- \" 要点概括这批变更做了什么\n");
        prompt.append("3. 除此之外不输出任何内容（不要分析过程、不要解释、不要代码围栏）\n");
        String languageName = LanguageConfigService.getLanguageDisplayName(getCommitOutputLanguage());
        prompt.append("4. 要点必须使用 ").append(languageName).append(" 撰写\n\n");
        for (String line : batchLines) {
            prompt.append(line).append("\n");
        }
        return prompt.toString();
    }

    /**
     * Build the merge prompt that reduces the full inventory and all batch
     * summaries into one conventional commit message.
     */
    private String buildMergePrompt(List<String> summaries, List<String> inventory) {
        StringBuilder prompt = new StringBuilder();
        prompt.append(BUILTIN_COMMIT_PROMPT);
        appendUserAndProjectPrompts(prompt);
        appendOutputLanguageRequirement(prompt);

        prompt.append("\n\n---\n\n");
        prompt.append("本次提交涉及 ").append(inventory.size())
                .append(" 个文件的变更。完整变更清单如下（格式：状态 路径 (+增/-删)，A=新增 M=修改 D=删除）：\n\n");
        prompt.append(cappedInventoryText(inventory));
        prompt.append("\n\n各批分析代理的概括结果（共 ").append(summaries.size()).append(" 批）：\n\n");
        for (int i = 0; i < summaries.size(); i++) {
            prompt.append("【第 ").append(i + 1).append(" 批】\n");
            prompt.append(summaries.get(i)).append("\n\n");
        }
        prompt.append("请将以上变更归纳为一个逻辑整体，选择最主要的一个 type，生成一条统一的 commit message。");

        appendOutputFormatRequirements(prompt);
        return prompt.toString();
    }

    /**
     * Render the inventory for prompts, capped at {@link #MAX_INVENTORY_CHARS}
     * with an overflow note so huge change sets stay within model limits.
     */
    private String cappedInventoryText(List<String> inventory) {
        StringBuilder text = new StringBuilder();
        int shown = 0;
        for (String line : inventory) {
            if (text.length() + line.length() + 1 > MAX_INVENTORY_CHARS) {
                break;
            }
            text.append(line).append("\n");
            shown++;
        }
        if (shown < inventory.size()) {
            text.append("… 其余 ").append(inventory.size() - shown).append(" 个文件从略");
        }
        return text.toString();
    }

    /**
     * Build the per-file change inventory ("M path (+a/-d)") for every change.
     * Computed locally without any AI call. Files that fail to load are listed
     * without line counts. Extracted for tests.
     */
    protected List<String> buildChangeInventory(List<Change> changes) {
        List<String> inventory = new ArrayList<>(changes.size());
        for (Change change : changes) {
            try {
                FilePath filePath = ChangesUtil.getFilePath(change);
                Change.Type changeType = change.getType();

                if (changeType == Change.Type.NEW) {
                    String content = readContentSafely(change.getAfterRevision());
                    inventory.add("A  " + filePath.getPath() + " (+" + countLines(content) + ")");
                } else if (changeType == Change.Type.DELETED) {
                    String content = readContentSafely(change.getBeforeRevision());
                    inventory.add("D  " + filePath.getPath() + " (-" + countLines(content) + ")");
                } else {
                    String before = readContentSafely(change.getBeforeRevision());
                    String after = readContentSafely(change.getAfterRevision());
                    if (before != null && after != null
                            && before.length() <= MAX_FILE_CONTENT_LENGTH
                            && after.length() <= MAX_FILE_CONTENT_LENGTH) {
                        int[] counts = countLineChanges(before, after);
                        if (counts[0] >= 0) {
                            inventory.add("M  " + filePath.getPath() + " (+" + counts[0] + "/-" + counts[1] + ")");
                        } else {
                            inventory.add("M  " + filePath.getPath() + " (+?/-?)");
                        }
                    } else {
                        inventory.add("M  " + filePath.getPath());
                    }
                }
            } catch (Exception e) {
                LOG.warn("Failed to inspect change for inventory: " + e.getMessage());
            }
        }
        return inventory;
    }

    /**
     * Build the per-file detail section appended after the generated commit
     * message, or null when the inventory is empty (nothing meaningful to show).
     */
    private String buildFileDetailSection(List<String> inventory) {
        if (inventory.isEmpty()) {
            return null;
        }
        StringBuilder detail = new StringBuilder();
        detail.append("\n\n").append(localized("commit.detailHeader", inventory.size()));
        int shown = Math.min(inventory.size(), MAX_DETAIL_LINES);
        for (int i = 0; i < shown; i++) {
            detail.append("\n").append(inventory.get(i));
        }
        if (inventory.size() > shown) {
            detail.append("\n").append(localized("commit.detailTruncated", inventory.size() - shown));
        }
        return detail.toString();
    }

    private static String readContentSafely(ContentRevision revision) {
        if (revision == null) {
            return null;
        }
        try {
            return revision.getContent();
        } catch (Exception e) {
            return null;
        }
    }

    private static int countLines(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        return content.split("\n").length;
    }

    /**
     * Count added/removed lines between two file versions using an LCS on
     * lines (two-row DP, O(min(n,m)) memory). Returns {added, deleted}, or
     * {-1, -1} when the inputs are too large to compare precisely.
     */
    static int[] countLineChanges(String before, String after) {
        String[] beforeLines = before.split("\n");
        String[] afterLines = after.split("\n");
        if ((long) beforeLines.length * (long) afterLines.length > MAX_LCS_CELLS) {
            return new int[]{-1, -1};
        }
        int lcs = lcsLength(beforeLines, afterLines);
        return new int[]{afterLines.length - lcs, beforeLines.length - lcs};
    }

    private static int lcsLength(String[] a, String[] b) {
        // Keep b the shorter dimension for memory
        if (a.length < b.length) {
            String[] tmp = a;
            a = b;
            b = tmp;
        }
        int[] prev = new int[b.length + 1];
        int[] curr = new int[b.length + 1];
        for (int i = 1; i <= a.length; i++) {
            String ai = a[i - 1];
            for (int j = 1; j <= b.length; j++) {
                curr[j] = ai.equals(b[j - 1]) ? prev[j - 1] + 1 : Math.max(prev[j], curr[j - 1]);
            }
            int[] tmp = prev;
            prev = curr;
            curr = tmp;
            java.util.Arrays.fill(curr, 0);
        }
        return prev[b.length];
    }

    /**
     * Call the AI service.
     */
    private void callAIService(String prompt, CommitMessageCallback callback) throws IOException {
        JsonObject commitAiConfig = getCommitAiConfig();
        String effectiveProvider = getResolvedCommitAiProvider(commitAiConfig);

        if (effectiveProvider == null) {
            callback.onError(localized("commit.noAvailableProvider"));
            return;
        }

        reportStage("commit.stage.connecting");

        if (PROVIDER_CODEX.equals(effectiveProvider)) {
            callCodexAPI(prompt, getResolvedCommitAiModel(commitAiConfig, PROVIDER_CODEX), callback);
            return;
        }

        callClaudeAPI(prompt, getResolvedCommitAiModel(commitAiConfig, PROVIDER_CLAUDE), callback);
    }

    protected JsonObject getCommitAiConfig() throws IOException {
        return settingsService.getCommitAiConfig();
    }

    private String getResolvedCommitAiProvider(JsonObject commitAiConfig) {
        if (commitAiConfig == null
                || !commitAiConfig.has("effectiveProvider")
                || commitAiConfig.get("effectiveProvider").isJsonNull()) {
            return null;
        }
        String provider = commitAiConfig.get("effectiveProvider").getAsString().trim();
        return provider.isEmpty() ? null : provider;
    }

    private String getResolvedCommitAiModel(JsonObject commitAiConfig, String provider) {
        if (commitAiConfig == null
                || !commitAiConfig.has("models")
                || !commitAiConfig.get("models").isJsonObject()) {
            return null;
        }
        JsonObject models = commitAiConfig.getAsJsonObject("models");
        if (!models.has(provider) || models.get(provider).isJsonNull()) {
            return null;
        }
        String model = models.get(provider).getAsString().trim();
        return model.isEmpty() ? null : model;
    }

    /**
     * Call the Claude API.
     */
    protected void callClaudeAPI(String prompt, String model, CommitMessageCallback callback) {
        ClaudeSDKBridge bridge = new ClaudeSDKBridge();
        // Let the timeout guard interrupt this bridge's channel if the request
        // never completes (wedged daemon or stalled child process).
        registerBridgeCleanup(() -> bridge.interruptChannel(COMMIT_CHANNEL_ID));
        try {
            // Collects assistant text across callback types, skipping thinking blocks
            CommitMessageCollector collector = new CommitMessageCollector();
            AtomicBoolean receivedFirstContent = new AtomicBoolean(false);

            // Use the 12-parameter sendMessage overload:
            // - model: resolved from the commit AI config
            // - streaming: false (non-streaming, returns complete result at once)
            // - disableThinking: follows the commit fast-mode setting
            bridge.sendMessage(
                COMMIT_CHANNEL_ID,          // channelId
                prompt,                     // message
                null,                       // sessionId (null = new session)
                project.getBasePath(),      // cwd
                null,                       // attachments (not needed)
                null,                       // permissionMode (use default)
                model,                      // model
                null,                       // openedFiles
                null,                       // agentPrompt
                false,                      // streaming (non-streaming mode)
                isCommitFastMode(),         // disableThinking (fast mode skips thinking)
                new MessageCallback() {
                    @Override
                    public void onMessage(String type, String content) {
                        if (collector.onMessage(type, content)
                                && receivedFirstContent.compareAndSet(false, true)) {
                            reportStage("commit.stage.receiving");
                        }
                    }

                    @Override
                    public void onError(String error) {
                        // Deliver the callback FIRST: daemon shutdown may block on a
                        // wedged process and must not delay or swallow the UI result.
                        try {
                            callback.onError(error);
                        } finally {
                            bridge.shutdownDaemon();
                        }
                    }

                    @Override
                    public void onComplete(SDKResult sdkResult) {
                        try {
                            String commitMessage = collector.collected().length() > 0
                                    ? collector.collected().trim()
                                    : sdkResult.finalResult.trim();

                            if (commitMessage.isEmpty()) {
                                callback.onError(localized("commit.emptyMessage"));
                            } else {
                                callback.onSuccess(cleanupCommitMessage(commitMessage));
                            }
                        } finally {
                            bridge.shutdownDaemon();
                        }
                    }
                }
            );
            reportStage("commit.stage.waiting");
        } catch (Exception e) {
            LOG.error("Failed to call Claude API", e);
            try {
                callback.onError(localized("commit.callApiFailed") + ": " + e.getMessage());
            } finally {
                bridge.shutdownDaemon();
            }
        }
    }

    /**
     * Call the Codex API.
     */
    protected void callCodexAPI(String prompt, String model, CommitMessageCallback callback) {
        CodexSDKBridge bridge = new CodexSDKBridge();
        // Let the timeout guard interrupt this bridge's channel if the request
        // never completes (stalled child process).
        registerBridgeCleanup(() -> bridge.interruptChannel(COMMIT_CHANNEL_ID));
        try {
            // Collects assistant text across callback types, skipping thinking blocks
            CommitMessageCollector collector = new CommitMessageCollector();
            AtomicBoolean receivedFirstContent = new AtomicBoolean(false);

            // CodexSDKBridge.sendMessage requires 11 parameters:
            // (channelId, message, threadId, cwd, attachments, permissionMode, model, agentPrompt, reasoningEffort, serviceTier, callback)
            bridge.sendMessage(
                COMMIT_CHANNEL_ID,          // channelId
                prompt,                     // message
                null,                       // threadId (null = new session)
                project.getBasePath(),      // cwd
                null,                       // attachments (not needed)
                null,                       // permissionMode (use default)
                model,                      // model
                null,                       // agentPrompt (not needed)
                getCodexReasoningEffort(),  // reasoningEffort ("low" in fast mode)
                null,                       // serviceTier (standard)
                new MessageCallback() {
                    @Override
                    public void onMessage(String type, String content) {
                        if (collector.onMessage(type, content)
                                && receivedFirstContent.compareAndSet(false, true)) {
                            reportStage("commit.stage.receiving");
                        }
                    }

                    @Override
                    public void onError(String error) {
                        // Deliver the callback FIRST: process cleanup may block on a
                        // stalled process and must not delay or swallow the UI result.
                        try {
                            callback.onError(error);
                        } finally {
                            bridge.cleanupAllProcesses();
                        }
                    }

                    @Override
                    public void onComplete(SDKResult sdkResult) {
                        try {
                            String commitMessage = collector.collected().length() > 0
                                    ? collector.collected().trim()
                                    : sdkResult.finalResult.trim();

                            if (commitMessage.isEmpty()) {
                                callback.onError(localized("commit.emptyMessage"));
                            } else {
                                callback.onSuccess(cleanupCommitMessage(commitMessage));
                            }
                        } finally {
                            bridge.cleanupAllProcesses();
                        }
                    }
                }
            );
            reportStage("commit.stage.waiting");
        } catch (Exception e) {
            LOG.error("Failed to call Codex API", e);
            try {
                callback.onError(localized("commit.callApiFailed") + ": " + e.getMessage());
            } finally {
                bridge.cleanupAllProcesses();
            }
        }
    }

    /**
     * Accumulates assistant text from the various callback payload shapes the
     * bridges emit. Plain "content"/"text" payloads are appended as-is; full
     * "assistant" message envelopes carry the raw SDK JSON (thinking blocks
     * included), so their text blocks are extracted instead. Raw protocol JSON
     * must never leak into the commit box.
     */
    static class CommitMessageCollector {
        private final StringBuilder result = new StringBuilder();

        /**
         * Handle one callback payload.
         *
         * @return true when assistant text was appended
         */
        boolean onMessage(String type, String content) {
            if (content == null || content.isEmpty()) {
                return false;
            }
            if ("content".equals(type) || "text".equals(type)) {
                if (isThinkingContent(content)) {
                    return false;
                }
                result.append(content);
                return true;
            }
            if ("assistant".equals(type)) {
                String text = extractAssistantText(content);
                if (text.isEmpty()) {
                    return false;
                }
                result.append(text);
                return true;
            }
            // thinking / thinking_delta / tool_* / status / usage etc. are ignored
            return false;
        }

        String collected() {
            return result.toString();
        }
    }

    /**
     * Extract the text blocks of a serialized assistant SDK message
     * ({code {"type":"assistant","message":{"content":[...]}}}), skipping
     * thinking/reasoning blocks. Mirrors the extraction in the Codex bridge.
     *
     * @return the joined text, or "" when the payload has none / is not JSON
     */
    private static String extractAssistantText(String assistantJson) {
        try {
            JsonObject msg = JsonParser.parseString(assistantJson).getAsJsonObject();
            if (!msg.has("message") || !msg.get("message").isJsonObject()) {
                return "";
            }
            JsonObject message = msg.getAsJsonObject("message");
            if (!message.has("content") || message.get("content").isJsonNull()) {
                return "";
            }
            JsonElement contentEl = message.get("content");
            if (contentEl.isJsonPrimitive()) {
                return contentEl.getAsString();
            }
            if (!contentEl.isJsonArray()) {
                return "";
            }
            StringBuilder text = new StringBuilder();
            for (JsonElement block : contentEl.getAsJsonArray()) {
                if (!block.isJsonObject()) {
                    continue;
                }
                JsonObject blockObj = block.getAsJsonObject();
                if (blockObj.has("type") && !blockObj.get("type").isJsonNull()
                        && "text".equals(blockObj.get("type").getAsString())
                        && blockObj.has("text") && !blockObj.get("text").isJsonNull()) {
                    if (text.length() > 0) {
                        text.append("\n");
                    }
                    text.append(blockObj.get("text").getAsString());
                }
            }
            return text.toString();
        } catch (Exception e) {
            LOG.debug("Failed to parse assistant message payload: " + e.getMessage());
            return "";
        }
    }

    /**
     * Clean up and extract the commit message.
     * Prioritizes extraction from XML tags, with multiple format fallbacks.
     */
    static String cleanupCommitMessage(String message) {
        if (message == null || message.isEmpty()) {
            return "";
        }

        String cleaned = message;

        // 0. Remove thinking markers first (e.g. "Thinking >" etc.)
        cleaned = removeThinkingMarkers(cleaned);

        // 0.1 Unescape JSON-escaped angle brackets so <commit> tags embedded in
        // serialized protocol payloads remain findable.
        cleaned = cleaned.replace("\\u003c", "<").replace("\\u003e", ">");

        // 1. First try to extract from <commit>...</commit> tags
        int startIdx = cleaned.indexOf(COMMIT_TAG_START);
        int endIdx = cleaned.indexOf(COMMIT_TAG_END);

        if (startIdx != -1 && endIdx != -1 && endIdx > startIdx) {
            cleaned = cleaned.substring(startIdx + COMMIT_TAG_START.length(), endIdx);
            // Convert literal \n to actual newlines
            return convertLiteralNewlines(cleaned.trim());
        }

        // 2. Fallback: try to extract from markdown code blocks
        if (cleaned.contains("```")) {
            int codeBlockStart = cleaned.indexOf("```");
            // Find the first newline after the code block opener
            int contentStart = cleaned.indexOf('\n', codeBlockStart);
            if (contentStart != -1) {
                int codeBlockEnd = cleaned.indexOf("```", contentStart);
                if (codeBlockEnd != -1) {
                    cleaned = cleaned.substring(contentStart + 1, codeBlockEnd);
                    return convertLiteralNewlines(cleaned.trim());
                }
            }
        }

        // 3. Fallback: try to extract the first conventional commit formatted line
        // Format: type(scope): description or type: description
        String[] lines = cleaned.split("\n");
        for (String line : lines) {
            String trimmedLine = line.trim();
            if (isConventionalCommitLine(trimmedLine)) {
                // After finding the first line, continue collecting the body until hitting analysis sections
                StringBuilder result = new StringBuilder(trimmedLine);
                int idx = java.util.Arrays.asList(lines).indexOf(line);
                boolean inBody = false;

                for (int i = idx + 1; i < lines.length; i++) {
                    String nextLine = lines[i].trim();
                    // Stop when hitting analysis keywords
                    if (isAnalysisSection(nextLine)) {
                        break;
                    }
                    // Empty line indicates body start
                    if (nextLine.isEmpty()) {
                        inBody = true;
                        result.append("\n");
                        continue;
                    }
                    // Collect body content
                    if (inBody && !nextLine.startsWith("#") && !nextLine.startsWith("*")) {
                        result.append("\n").append(nextLine);
                    } else if (!inBody) {
                        // Not in body yet but hit a non-empty line, means single-line commit
                        break;
                    }
                }
                return convertLiteralNewlines(result.toString().trim());
            }
        }

        // 4. Last resort fallback: return the first few lines of raw content (excluding analysis sections)
        StringBuilder fallback = new StringBuilder();
        for (String line : lines) {
            String trimmedLine = line.trim();
            if (isAnalysisSection(trimmedLine)) {
                break;
            }
            if (!trimmedLine.isEmpty()) {
                fallback.append(trimmedLine).append("\n");
            }
            // Take at most 5 lines
            if (fallback.toString().split("\n").length >= 5) {
                break;
            }
        }

        return convertLiteralNewlines(fallback.toString().trim());
    }

    /**
     * Convert literal \n characters to actual newlines and clean up excess blank lines.
     */
    private static String convertLiteralNewlines(String text) {
        if (text == null) {
            return null;
        }
        // Convert literal \n (two characters) to actual newlines
        String result = text.replace("\\n", "\n");

        // Remove leading blank lines
        result = result.replaceFirst("^\\n+", "");

        // Collapse multiple consecutive blank lines into a single one (preserve the conventional commit title/body separator)
        result = result.replaceAll("\\n{3,}", "\n\n");

        return result.trim();
    }

    /**
     * Check whether a line follows the conventional commit format.
     */
    private static boolean isConventionalCommitLine(String line) {
        if (line == null || line.isEmpty()) {
            return false;
        }
        // Match: feat:, fix:, refactor:, feat(scope):, etc.
        String[] types = {"feat", "fix", "refactor", "docs", "test", "chore", "perf", "ci", "style", "build"};
        for (String type : types) {
            if (line.startsWith(type + ":") || line.startsWith(type + "(")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Check whether a line belongs to an analysis section (content to exclude).
     */
    private static boolean isAnalysisSection(String line) {
        if (line == null) {
            return false;
        }
        String[] analysisKeywords = {
            "分析说明", "变更特征", "分析：", "说明：", "解释：", "备注：",
            "Analysis:", "Explanation:", "Note:", "---", "===",
            "1. 类型", "2. Scope", "3. 描述", "4. Body",
            "• ", "- 无需", "- 不涉及"
        };
        for (String keyword : analysisKeywords) {
            if (line.contains(keyword)) {
                return true;
            }
        }
        // Check for numbered list items (e.g. "1. xxx")
        if (line.matches("^\\d+\\.\\s+.*")) {
            return true;
        }
        return false;
    }

    /**
     * Check whether the content is a thinking/reasoning process.
     */
    private static boolean isThinkingContent(String content) {
        if (content == null || content.isEmpty()) {
            return false;
        }
        // Common markers for thinking/reasoning content
        String[] thinkingMarkers = {
            "思考", "thinking", "Thinking", "<thinking>", "</thinking>",
            "让我分析", "让我思考", "我来分析", "首先分析",
            "Let me think", "Let me analyze"
        };
        String trimmed = content.trim();
        for (String marker : thinkingMarkers) {
            if (trimmed.startsWith(marker) || trimmed.contains("<thinking>")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Remove thinking markers and their content.
     */
    private static String removeThinkingMarkers(String content) {
        if (content == null || content.isEmpty()) {
            return content;
        }

        String result = content;

        // Remove <thinking>...</thinking> tags and their content
        while (result.contains("<thinking>") && result.contains("</thinking>")) {
            int start = result.indexOf("<thinking>");
            int end = result.indexOf("</thinking>") + "</thinking>".length();
            if (start < end) {
                result = result.substring(0, start) + result.substring(end);
            } else {
                break;
            }
        }

        // Remove UI thinking markers like "Thinking >" etc.
        String[] uiMarkers = {"思考 ▸", "思考▸", "思考 ►", "思考►", "Thinking ▸", "Thinking▸"};
        for (String marker : uiMarkers) {
            result = result.replace(marker, "");
        }

        // Remove leading blank lines
        result = result.replaceFirst("^\\s*\\n+", "");

        return result.trim();
    }
}
